DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS CREDENTIALS;

CREATE TABLE CREDENTIALS
(
  USER_ID BIGINT AUTO_INCREMENT,
  EMAIL VARCHAR(30),
  PASSWORD_HASH VARCHAR(64),
  CONSTRAINT CREDENTIALS_PK PRIMARY KEY(USER_ID),
  CONSTRAINT CREDENTIALS_UNIQ UNIQUE (EMAIL)
);

CREATE TABLE PROFILE
(
  USER_ID BIGINT,
  FIRST_NAME VARCHAR(20) NOT NULL ,
  LAST_NAME VARCHAR(20),
  GENDER TINYINT, # 1 FOR MALE, 0 FOR FEMALE
  COUNTRY VARCHAR(20),
  CONSTRAINT PROFILE_PK PRIMARY KEY(USER_ID),
  CONSTRAINT PROFILE_FK FOREIGN KEY(USER_ID) REFERENCES CREDENTIALS(USER_ID)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

